### ISSUE TITLE
Error running local testnet

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/cosmos-ui#16]
Version:
```
Tendermint: 0.11.1-d4634dc6
Basecoin: 0.7.1-6c667b8
Baseserver: 0.7.1-6c667b8
Cosmos-ui: 9f45165
```

Steps:
```
npm i

npm run local
```

Error:
```
➜  cosmos-ui git:(test-fix) ✗ npm run local

> cosmos-ui-electron@0.1.0 local /Users/adrian/Code/cosmos/cosmos-ui
> npm run testnet local


> cosmos-ui-electron@0.1.0 testnet /Users/adrian/Code/cosmos/cosmos-ui
> node tasks/testnet.js "local"

Starting webpack-dev-server...

webpack  fallbackLoader option has been deprecated - replace with "fallback"

webpack  loader option has been deprecated - replace with "use"

webpack  Project is running at http://localhost:9080/

webpack  webpack output is served from /
         Content not from webpack is served from /Users/adrian/Code/cosmos/cosmos-ui/app/dist

webpack  (node:499) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
         parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

webpack  Hash: 2ae48ca3a59297d28723
         Version: webpack 2.7.0
         Time: 14284ms
                                     Asset     Size  Chunks                    Chunk Names
             fonts/fontawesome-webfont.eot   166 kB          [emitted]
              imgs/fontawesome-webfont.svg   444 kB          [emitted]  [big]
           fonts/MaterialIcons-Regular.ttf   128 kB          [emitted]
          fonts/MaterialIcons-Regular.woff  57.6 kB          [emitted]
         fonts/MaterialIcons-Regular.woff2  44.3 kB          [emitted]
             fonts/fontawesome-webfont.ttf   166 kB          [emitted]
           fonts/fontawesome-webfont.woff2  77.2 kB          [emitted]
            fonts/fontawesome-webfont.woff    98 kB          [emitted]
                               renderer.js  11.2 MB       0  [emitted]  [big]  renderer
                                index.html  1.63 kB          [emitted]
         chunk    {0} renderer.js (renderer) 3.87 MB [entry] [rendered]
             [6] ./app/~/babel-runtime/helpers/extends.js 544 bytes {0} [built]
            [46] ./app/~/babel-runtime/regenerator/index.js 49 bytes {0} [built]
           [380] ./app/src/renderer/main.js 2.52 kB {0} [built]
           [381] (webpack)-dev-server/client?http://localhost:9080 5.83 kB {0} [built]
           [382] (webpack)/hot/dev-server.js 1.57 kB {0} [built]
           [446] ./app/~/strip-ansi/index.js 161 bytes {0} [built]
           [452] ./app/src/renderer/node.js 1.85 kB {0} [built]
           [453] ./app/src/renderer/routes.js 3.01 kB {0} [built]
           [611] ./~/loglevel/lib/loglevel.js 6.74 kB {0} [built]
           [846] ./~/vuelidate/lib/index.js 14 kB {0} [built]
           [863] (webpack)-dev-server/client/overlay.js 3.6 kB {0} [built]
           [864] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
           [866] (webpack)/hot nonrecursive ^\.\/log$ 160 bytes {0} [built]
           [867] (webpack)/hot/log-apply-result.js 1.02 kB {0} [built]
           [896] multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./app/src/renderer/main.js 52 bytes {0} [built]
              + 882 hidden modules
         Child html-webpack-plugin for "index.html":
             chunk    {0} index.html 542 kB [entry] [rendered]
                 [0] ./~/lodash/lodash.js 540 kB {0} [built]
                 [1] ./~/html-webpack-plugin/lib/loader.js!./app/index.ejs 2.2 kB {0} [built]
                 [2] (webpack)/buildin/module.js 517 bytes {0} [built]

webpack  webpack: Compiled successfully.

Starting electron...
  (network path: ./app/networks/local)

electron  root exists (/Users/adrian/.cosmos-ui-dev)

electron  backing up data to "/Users/adrian/.cosmos-ui-dev_backup_1"

electron  initializing data directory (/Users/adrian/.cosmos-ui-dev)

electron  spawning /Users/adrian/go/bin/basecoin with args ""init" "1B1BE55F969F54064628A63B9559E7C21C925165" "--home" "/Users/adrian/.cosmos-ui-dev""

electron  Error: Initialization of basecoint failed:
              at /Users/adrian/Code/cosmos/cosmos-ui/app/src/main/index.js:384:13
              at <anonymous>
              at process._tickCallback (internal/process/next_tick.js:109:7)
              at Module.runMain (module.js:607:11)
              at run (bootstrap_node.js:431:7)
              at startup (bootstrap_node.js:155:9)
              at bootstrap_node.js:551:3

exited electron app/src/main/index.dev.js 1
```

**Comment by nylira** [comment]
I think this is resolved. Can you try to run `npm run testnet` now?
