### ISSUE TITLE
occasional ECONNREFUSED error

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#363]
sometimes, i see these errors. the UI still runs, but nothing really works. restarting the UI usually fixes it.

```
gaia: fatal error: concurrent map writes

electron  gaia: 
          goroutine 32 [running]:
          runtime.throw(0x494fc15, 0x15)
          	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc420a915a0 sp=0xc420a91580 pc=0x402d505
          runtime.mapassign_faststr(0x4843c60, 0xc420a6a090, 0xc4209c4ff0, 0x28, 0xc4209c4ff0)

```
...
```
goroutine 33 [IO wait]:
          internal/poll.runtime_pollWait(0x5548e18, 0x72, 0x0)
          	/usr/local/go/src/runtime/netpoll.go:173 +0x57
          internal/poll.(*pollDesc).wait(0xc42058b018, 0x72, 0xffffffffffffff00, 0x4f36700, 0x4f2f9f8)
          	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
          internal/poll.(*pollDesc).waitRead(0xc42058b018, 0xc420a13d00, 0x1, 0x1)
          	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
          internal/poll.(*FD).Read(0xc42058b000, 0xc420a13de1, 0x1, 0x1, 0x0, 0x0, 0x0)
          	/usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
          net.(*netFD).Read(0xc42058b000, 0xc420a13de1, 0x1, 0x1, 0xc420010060, 0x0, 0x4f33801)
          	/usr/local/go/src/net/fd_unix.go:202 +0x52
          net.(*conn).Read(0xc42000e590, 0xc420a13de1, 0x1, 0x1, 0x0, 0x0, 0x0)
          	/usr/local/go/src/net/net.go:176 +0x6d
          net/http.(*connReader).backgroundRead(0xc420a13dd0)
          	/usr/local/go/src/net/http/server.go:660 +0x62
          created by net/http.(*connReader).startBackgroundRead
          	/usr/local/go/src/net/http/server.go:656 +0xd8

electron  gaia exited with code 2

electron  Error: connect ECONNREFUSED 127.0.0.1:8998
              at Object.exports._errnoException (util.js:1050:11)
              at exports._exceptionWithHostPort (util.js:1073:20)
              at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

```

**Comment by mappum** [comment]
This is a tendermint bug. It was fixed in `0.15.0`, so it shouldn't happen with gaia `0.5.0` and up.

https://github.com/tendermint/tendermint/issues/1006

**Comment by jolesbi** [comment]
@mappum i think you just need to confirm that we can close this!

**Comment by mappum** [comment]
Confirmed that gaia 0.5.0 upgraded to Tendermint 0.15.0, which is the release with the fix.
