### ISSUE TITLE
npm run local doesn't work on a clean setup.

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmos-ui#7]
```
$ node -v
v8.7.0
$ npm run local

> cosmos-ui-electron@0.1.0 local /home/ethan/vue/cosmos-ui
> npm run testnet local


> cosmos-ui-electron@0.1.0 testnet /home/ethan/vue/cosmos-ui
> node tasks/testnet.js "local"

module.js:529
    throw err;
    ^

Error: Cannot find module 'event-to-promise'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ethan/vue/cosmos-ui/tasks/runner.js:7:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cosmos-ui-electron@0.1.0 testnet: `node tasks/testnet.js "local"`
npm ERR! Exit status 1
```

**Comment by ethanfrey** [comment]
Got it to build by running `npm install event-to-promise`

**Comment by ethanfrey** [comment]
Now it dies on startup with no error message...

```
webpack  Hash: 667ff9f23c1946586eef
         Version: webpack 2.7.0
         Time: 9043ms
                                     Asset     Size  Chunks                    Chunk Names
             fonts/fontawesome-webfont.eot   166 kB          [emitted]         
              imgs/fontawesome-webfont.svg   444 kB          [emitted]  [big]  
           fonts/MaterialIcons-Regular.ttf   128 kB          [emitted]         
          fonts/MaterialIcons-Regular.woff  57.6 kB          [emitted]         
         fonts/MaterialIcons-Regular.woff2  44.3 kB          [emitted]         
             fonts/fontawesome-webfont.ttf   166 kB          [emitted]         
           fonts/fontawesome-webfont.woff2  77.2 kB          [emitted]         
            fonts/fontawesome-webfont.woff    98 kB          [emitted]         
                               renderer.js  11.2 MB       0  [emitted]  [big]  renderer
                                index.html  1.62 kB          [emitted]         
         chunk    {0} renderer.js (renderer) 3.87 MB [entry] [rendered]
             [6] ./app/~/babel-runtime/helpers/extends.js 544 bytes {0} [built]
            [46] ./app/~/babel-runtime/regenerator/index.js 49 bytes {0} [built]
           [380] ./app/src/renderer/main.js 2.52 kB {0} [built]
           [381] (webpack)-dev-server/client?http://localhost:9080 5.83 kB {0} [built]
           [382] (webpack)/hot/dev-server.js 1.57 kB {0} [built]
           [446] ./app/~/strip-ansi/index.js 161 bytes {0} [built]
           [452] ./app/src/renderer/node.js 1.85 kB {0} [built]
           [453] ./app/src/renderer/routes.js 3.01 kB {0} [built]
           [612] ./~/loglevel/lib/loglevel.js 6.74 kB {0} [built]
           [848] ./~/vuelidate/lib/index.js 14 kB {0} [built]
           [865] (webpack)-dev-server/client/overlay.js 3.6 kB {0} [built]
           [866] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
           [868] (webpack)/hot nonrecursive ^\.\/log$ 160 bytes {0} [built]
           [869] (webpack)/hot/log-apply-result.js 1.02 kB {0} [built]
           [898] multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./app/src/renderer/main.js 52 bytes {0} [built]
              + 884 hidden modules
         Child html-webpack-plugin for "index.html":
             chunk    {0} index.html 542 kB [entry] [rendered]
                 [0] ./~/lodash/lodash.js 540 kB {0} [built]
                 [1] ./~/html-webpack-plugin/lib/loader.js!./app/index.ejs 2.2 kB {0} [built]
                 [2] (webpack)/buildin/module.js 517 bytes {0} [built]
         webpack: Compiled successfully.

Starting electron...
  (network path: ./app/networks/local)

exited electron app/src/main/index.dev.js 1
```

**Comment by ethanfrey** [comment]
FYI, on ubuntu:

```
$ tendermint version
0.11.1-d4634dc6
$ basecoin version
0.7.1-6c667b8
$ baseserver version
0.7.1-6c667b8
```

**Comment by mappum** [comment]
The missing dependency got added in 8ab636fdfe449a61b5fb0fa84f7066fd78e6115b
